### ISSUE TITLE
see what was removed

### ISSUE THREAD

**Issue by lavendelchen** [ombhd/Cleaner_42#9]
would like to see what was removed after it was cleaned, or have an option/command for that

**Comment by ombhd** [comment]
Thanks for your suggestion, but my question is why we should add such feature to the script?
It will make it more time-consuming to clean things on your session.
The important thing is that the script cleans only the things listed in the repo README.

**Comment by lavendelchen** [comment]
not sure what you mean by "time consuming". i'm not looking for a yes/no thing where you have to decide what gets deleted, but just when the clean is completed to see what folders or files got deleted, and maybe how much space each folder/file took. makes it more transparent and less "we did _something_ and now 3GB are gone"-like. if by "time consuming" you mean run-time, i don't think this feature should add so much to it?

**Comment by ombhd** [comment]
Could you please open a PR for it?

**Comment by recursive-beast** [comment]
I've opened a #11  for this

**Comment by ombhd** [comment]
PR merged, thanks to @recursive-beast who implemented the functionality
